version: "3"

services:
  front-siednl:
    container_name: front-siednl
    image: front-siednl
    build:
      context: .
    environment:
<<<<<<< HEAD
      REACT_APP_APPLICATION_BACK: "http://10.200.4.105:5000"
      REACT_APP_APPLICATION_FRONT_LOGIN: "http://10.200.4.106"
=======
      REACT_APP_APPLICATION_BACK: "http://10.200.4.105:8000"
      REACT_APP_APPLICATION_FRONT_LOGIN: "http://172.18.0.2"
>>>>>>> b7008dc92fb72c168ceb078a319f6bcccf5c6dc0
      REACT_APP_APPLICATION_MID: "http://10.200.4.105:7000"
      REACT_APP_APPLICATION_LOGIN: "http://10.200.4.105:5000"
      REACT_APP_APPLICATION_FILL: "http://10.200.4.105:7001"
      REACT_APP_APPLICATION_QA_LOGIN: "http://10.200.4.164:5000"
      REACT_APP_APPLICATION_MIR: "http://10.200.4.105:9090"
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3000