version: "3.8"

services:
  front-siednl:
    container_name: front-qa
    image: front-qa
    build:
      context: .
      target: qa
    environment:
      REACT_APP_APPLICATION_BACK: "10.200.4.164:3000"
      REACT_APP_APPLICATION_MID: "http://10.200.4.105:7000"
      REACT_APP_APPLICATION_LOGIN: "http://10.200.4.105:5000"
      REACT_APP_APPLICATION_FILL: "http://10.200.4.105:7001"
      REACT_APP_APPLICATION_QA_LOGIN: "http://10.200.4.164:5000"
      REACT_APP_APPLICATION_MIR: "http://10.200.4.105:9090"


    volumes:
      - ./src:/app/src
    ports:
      - 3500:3000