version: "3"

services:
  front-siednl:
    container_name: front-siednl
    image: front-siednl
    build:
      context: .
    environment:
      REACT_APP_APPLICATION_BACK: "http://10.200.4.164:8000"
      REACT_APP_APPLICATION_FRONT_LOGIN: "http://10.200.4.165"
      REACT_APP_APPLICATION_MID: "http://10.200.4.105:7000"
      REACT_APP_APPLICATION_LOGIN: "http://10.200.4.164:5000"
      REACT_APP_APPLICATION_FILL: "http://10.200.4.105:7001"
      REACT_APP_APPLICATION_QA_LOGIN: "http://10.200.4.164:5000"
      REACT_APP_APPLICATION_CORREO: "http://10.200.4.164:8000"
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3001
