// Generated by https://quicktype.io

  export default interface DataUsuariosTiCentral {
    Id:                string;
    IdUsuarioTiCentral:string;
    Nombre:            string;
    ApellidoPaterno:   string;
    ApellidoMaterno:   string;
    CorreoElectronico: string;
    NombreUsuario:     string;
    Cargo:             string;
    Telefono:          string;
    Ext:               string;
    Curp:              string;
    Rfc:               string;
    Celular:           string;
    IdRol:             string;
    Rol:               string;
    IdInstitucion:     string;
    NombreInstitucion: string;
    CreadoPor:         string;
    ModificadoPor:     string;
  }

  export interface IdataUser {
    Id:                string;
    Nombre:            string;
    ApellidoPaterno:   string;
    ApellidoMaterno:   string;
    CorreoElectronico: string;
    NombreUsuario:     string;
    Telefono:          string;
    Ext:               string;
    Curp:              string;
    Rfc:               string;
    Celular:           string;
  }

  