// Generated by https://quicktype.io

  export interface DataUsuariosTiCentral {
    Id:                string;
    EstaActivo:        number;
    Nombre:            string;
    ApellidoPaterno:   string;
    ApellidoMaterno:   string;
    NombreUsuario:     string;
    CorreoElectronico: string;
    CreadoPor:         string;
    ModificadoPor:     string;
  }

  type Order = "asc" | "desc";

  export interface EnhancedTableProps {
    numSelected: number;
    onRequestSort: (
      event: React.MouseEvent<unknown>,
      property: keyof DataUsuariosTiCentral
    ) => void;
    onSelectAllClick: (event: React.ChangeEvent<HTMLInputElement>) => void;
    order: Order;
    orderBy: string;
    rowCount: number;
  }

  export interface HeadCell {
    disablePadding: boolean;
    Id: keyof DataUsuariosTiCentral;
    label: string;
    numeric: boolean;
  }